services:
  mongodb:
    image: mongo:latest
    container_name: url-shortner-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Admin
    volumes:
      - url-shortner-mongo-data:/data/db

volumes:
  url-shortner-mongo-data: